### ISSUE TITLE
Später für die Doku :: Matomo Cookies

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/iwcc#12]
Matomo-Cookies
https://matomo.org/faq/general/faq_146/

**Comment by IngoWinter** [comment]
Wenn du die Matomo Cookies irgenwann irgendwo fertig hast, nehme ich gerne einen Dump der Cookiegroup/Cookie DB und pack das mit in die install.sql.

**Comment by skerbis** [comment]
@IngoWinter ja ok. Bitte offen lassen. Ich versuche was allgemeines zu bauen

**Comment by IngoWinter** [comment]
Vielleicht irgendwas JSON artiges als Teil des Repos, so dass jeder seine Cookies und Cookiegruppen reinkippen kann? Wie hier: https://github.com/FriendsOfREDAXO/community/tree/master/_directory

**Comment by skerbis** [comment]
YAML

```YAML
-
  name: _pk_id
  time: 13 Monate
  desc: Speichert für jeden Besucher der Website eine anonyme ID. Anhand der ID können Seitenaufrufe einem Besucher zugeordnet werden.
-
  name: _pk_ses
  time: 6 Monate
  desc: Zur Speicherung des Verweises der ursprünglich zum Besuch der Website verwendet wurde.
-
  name: _pk_ses
  time: 30 Minuten
  desc: Hilfscookie für temporäre Daten
-
  name:  _pk_cvar
  time: 30 Minuten
  desc: Hilfscookie für temporäre Daten
-
  name:  _pk_hsr
  time: 30 Minuten
  desc: Hilfscookie für temporäre Daten
```
